config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	get 'books/about'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :books
	root 'books#index'

	resources :users, only: [:show, :new, :edit, :update]

	post 'books/_new' => 'books#create'
	get 'books/_new' => 'books#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :opinion, {presence: true, length: {maximum: 200}}
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_many :books
	attachment :profile_image
	validates :name, {presence: true, length: {in: 2..20}}
	validates :introduction, length: {maximum: 50}

	def books
		return Book.where(user_id: self.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from ActiveRecord::RecordNotFound do |exception|
	redirect_to :root
	end

	before_action :authenticate_user!, except: [:about, :index]
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])

	end

	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
      @book = Book.find(params[:id])
      @newbook = Book.new
      @user = User.find_by(id: @book.user_id)
  end

  def new
      @user = current_user
      @book = Book.new
      @books = Book.all
  end

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if
        @book.save
        flash[:notice] = '新規のBookが投稿されました。'
        redirect_to book_path(@book)

      else
        @user = current_user
        @book = Book.new
        redirect_to user_path(current_user.id)
      end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      book = Book.find(params[:id])
      book.update(book_params)
      flash[:notice] = 'Bookが更新されました。'
      redirect_to book_path(book)
  end

  def destroy
      book = Book.find(params[:id])
      book.destroy
      flash[:notice] = 'Bookが削除されました。'
      redirect_to new_book_path
  end

  def about
  end



  private
      def book_params
        params.require(:book).permit(:title, :opinion, :user_id)
      end
      def correct_user
       book = Book.find(params[:id])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
		@book = Book.new
	end

	def new
		@user = current_user
		@users = User.all
		@book = Book.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if
			@user.update(user_params)
			redirect_to user_path(@user.id)
		else
			flash[:notice] = '名前は2文字以上、20文字以内・自己紹介は50文字以内にしてください。'
			render :edit
		end
	end



	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless @user == current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_footer.html.erb
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="">
            <%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home" %>
          </li>
          <li class="">
            <%= link_to ' Users', new_user_path, class: "glyphicon glyphicon-user" %>
          </li>
          <li class="">
            <%= link_to ' Books', new_book_path, class: "glyphicon glyphicon-book" %>
          </li>
          <li class="">
            <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
          </li>
        <% else %>
          <li class="">
            <%= link_to ' Home', books_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li class="">
            <%= link_to ' About', books_about_path, class: "glyphicon glyphicon-link" %>
          </li>
          <li class="">
            <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
          </li>
          <li class="">
            <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/books/_new.html.erb
<h2>New book</h2>
<%= form_for(book) do |f| %>
	<div class="field row">
		<label for="book_title">Title</label>
		<%= f.text_field :title, class:"col-xs-12" %>
	</div>
	<div class="field row">
		<label for="book_opinion">Opinion</label>
		<%= f.text_area :opinion, class:"col-xs-12" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_notice.html.erb
<% flash.each do |key, value| %>
  <p class="notice"><%= content_tag(:div, value, class: "#{key}") %></p>
<% end %>

app/views/books/about.html.erb
<!-- Aboutページ -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>

<div class="body">
	<div class='container'>
		<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>
	</div>
</div>

<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/books/edit.html.erb
<% if current_user == @book.user%>
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>
<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class='row'>
			<div class='col-md-6 col-md-offset-3'>
				<h1>Editing Book</h1>
					<%= form_for(@book) do |f| %>
						<div class="field row">
							<label for="book_title">Title</label>
						    <%= f.text_field :title %>
						</div>
						<div class="field row">
						    <label for="book_opinion">Opinion</label>
						    <%= f.text_area :opinion %>
						</div>
						<div class="actions row">
						    <%= f.submit 'Update Book' %>
						</div>

					<% end %>
					<%= link_to "Show", book_path(@book) %> |
					<%= link_to "Book", book_path(@book) %>
			</div>
		</div>
	</div>
</div>

<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

<% else %>
<p>他人の投稿は編集・削除できません。<%= link_to "Back", root_path %></p>

<% end %>

app/views/books/index.html.erb
<!-- サイトトップ　books/indexページ -->

<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>
<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class="row">
			<div class='top-message col-md-offset-3 col-md-6'>
				<h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
				<p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
				<p>you can share and exchange  your opinions , inpressions , and emotions</p>
				<p> about varioius books!</p>

				<div class="btn-wrapper">
					<div class="row">
						<p><a class="btn btn-info col-xs-10 col-xs-offset-1" href="/users/sign_in">Log in</a></p>
					</div>
					<div class="row">
						<p><a class="btn btn-success col-xs-10 col-xs-offset-1" href="/users/sign_up">Sign Up</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/books/new.html.erb
<!-- book/new -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>

<div class="body">
	<div class='container'>
		<%= render 'books/notice' %>
		<div class='row'>

			<div class='col-xs-3'>
				<div class="user_info">
					<h2>User info</h2>
					<table class='table'>
						<tr>
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
						</tr>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class='row'>
						<% if @user.id == current_user.id %>
							<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% else %>
							<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% end %>
				    </div>
				</div>

				<div class="new_book">
					<%= render 'books/new', book: @book %>
				</div>
			</div>

			<!-- 右　全ブックの一覧　Image title　opinion-->
			<div class='col-xs-9'>
				<h2>Books</h2>

				<table class='table table-hover table-inverse'>
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<% @books.each do |book| %>
						<tbody>
							<tr>
								<!-- 投稿ユーザーのshowページへリンク、プロフ画像の表示 -->
								<td><a href=""><img class="attachment user profile_image fallback" /></a></td>
								<td><%= link_to book.title, book_path(book) %></td>
								<td><%= book.opinion %></td>
							</tr>
						</tbody>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>


<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/books/show.html.erb
<!-- book/show -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>

<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class='row'>

			<div class='col-xs-3'>
				<div class="user_info">
					<h2>User info</h2>
					<table class='table'>
						<tr>
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
						</tr>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class='row'>
						<% if @user.id == current_user.id %>
							<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% else %>
							<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% end %>
				    </div>
				</div>
				<div class="new_book">
					<%= render 'books/new', book: @newbook %>
				</div>
			</div>

			<!-- 右　Book detail 自分の投稿のみedit,destroyボタン表示-->
			<div class='col-xs-9'>
				<h2>Book detail</h2>
				<table class='table'>
					<tr>
						<td>
							<a href="">
								<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg", size: '40x40' %>
								<br><%= @user.name %>
							</a><!-- user/showにリンクをつける -->
						</td>
						<td><%= @book.title %></td>
						<td><%= @book.opinion %></td>

						<% if @book.user == current_user %>
							<td><%= link_to "Edit", edit_book_path(@book) %></td>
							<td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
							<!-- 他人のブックは削除・編集できないようにする -->
						<% end %>

					</tr>
				</table>
			</div>

		</div>
	</div>
</div>

<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<!-- user/edit -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>


<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class="col-xs-3">
			<h2>User info</h2>

			<%= form_for(@user) do |f| %><!-- <form class="edit_user"> -->
				<div class="field">
					<label for="user_name">Name</label>
					<%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
				</div>

				<div class="field">
					<label for="user_image">Image</label>
					<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
				</div>

				<div class="field">
					<label for="user_introduction">Introduction</label>
					<%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"自己紹介"%>
				</div>

				<div class="actions">
					<%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/users/new.html.erb
<!-- user/new -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>

<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class="row">

			<div class='col-xs-3'>
				<div class="user_info">
					<h2>User info</h2>
					<table class='table'>
						<tr>
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
						</tr>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class='row'>
						<% if @user.id == current_user.id %>
							<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% else %>
							<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% end %>
				    </div>
				</div>
				<div class="new_book">
					<%= render 'books/new', book: @book %>
				</div>
			</div>

			<div class='col-xs-9'>
				<h2>Users</h2>

				<table class='table'>
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<% @users.each do |user| %>
						<tbody>
							<tr>
								<td>
									<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg", size: '40x40' %>
								</td>
								<td><%= user.name %></td>
								<td><%= link_to "Show", user_path(user) %></td>
							</tr>
						</tbody>
					<% end %>

				</table>
			</div>
		</div>
	</div>
</div>

<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>

app/views/users/show.html.erb
<!-- user/show -->
<!-- header  部分テンプレート　_header.html.erb -->
<%= render 'books/header', books: @books %>

<div class="body">
	<div class="container">
		<%= render 'books/notice' %>
		<div class='row'>
			<div class='col-xs-3'>
				<div class="user_info">
					<h2>User info</h2>
					<table class='table'>
						<tr>
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
						</tr>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class='row'>
						<% if @user.id == current_user.id %>
							<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% else %>
							<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
						<% end %>
				    </div>
				</div>
				<div class="new_book">
					<%= render 'books/new', book: @book %>
				</div>
			</div>

			<!-- 右　投稿ブック一覧　Image title opinion　-->
			<div class='col-xs-9'>
				<h2>Books</h2>

				<table class='table table-hover table-inverse'>
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<% @user.books.each do |book| %>
						<tbody>
							<tr>
								<td><a href=""><img class="attachment user profile_image fallback" /></a></td>
								<td><%= link_to book.title, book_path(book) %></td>
								<td><%= book.opinion %></td>
							</tr>
						</tbody>
					<% end %>

				</table>
			</div>
		</div>
	</div>
</div>
<!-- hoofer  部分テンプレート　_footer.html.erb -->
<%= render 'books/footer' %>